<?php
/*
Template Name: catalogs Page
Template Post Type: page
*/

// files are not executed directly
if ( ! defined( 'ABSPATH' ) ) {	die( 'Invalid request.' ); }

/* -----------------------------------------------------------------------------
# Front Page
----------------------------------------------------------------------------- */

// Jawda header
get_my_header();

// Post Loop
while ( have_posts() ) : the_post();

// Page Header
get_my_page_header();

// End Loop
endwhile;

// Reset My Data
wp_reset_postdata();

?>
    <div class="projectspage">
      <div class="container">
    		<div class="row">
            <?php
         $current_page = function_exists( 'aqarand_get_current_paged' ) ? aqarand_get_current_paged() : 1;
         $current_page = max( 1, (int) $current_page );

         $main_query_paged = get_query_var( 'paged' );
         $main_query_page  = get_query_var( 'page' );

         $loop  = new WP_Query(
             array(
                 'post_type'           => 'catalogs',
                 'posts_per_page'      => 9,
                 'paged'               => $current_page,
                 'page'                => $current_page,
                 'post_status'         => 'publish',
                 'orderby'             => 'date', // modified | title | name | ID | rand
                 'order'               => 'DESC',
                 'no_found_rows'       => false,
                 'ignore_sticky_posts' => true,
             )
         );
       ?>
       <?php if ($loop->have_posts()): while ($loop->have_posts()) : $loop->the_post(); ?>
         <div class="col-md-4 projectbxspace">
            <?php get_my_article_box(); ?>
         </div>
            <?php endwhile; ?>
            <?php if ($loop->max_num_pages > 1) : // custom pagination  ?>
         <div class="col-md-12 center">
           <div class="blognavigation">
            <?php
             global $wp_query, $paged, $page;
               $orig_query = $wp_query; // fix for pagination to work
               $orig_paged = isset( $paged ) ? $paged : null;
               $orig_page  = isset( $page ) ? $page : null;
               $wp_query   = $loop;

               $current = max( 1, min( $current_page, (int) $loop->max_num_pages ) );

               $paged = $current;
               $page  = $current;
               set_query_var( 'paged', $current );
               set_query_var( 'page', $current );

               $pagination = '';

               if ( function_exists( 'theme_pagination' ) ) {
                   ob_start();
                   theme_pagination();
                   $pagination = trim( ob_get_clean() );
               }

               if ( '' === $pagination ) {
                   $big     = 999999999;
                   $format  = get_option( 'permalink_structure' ) ? 'page/%#%/' : '&paged=%#%';
                   $pagination = paginate_links(array(
                       'base'      => str_replace( $big, '%#%', esc_url( get_pagenum_link( $big ) ) ),
                       'format'    => $format,
                       'current'   => $current,
                       'total'     => (int) $loop->max_num_pages,
                       'mid_size'  => 2,
                       'end_size'  => 1,
                       'prev_text' => is_rtl() ? 'السابق' : '« Previous',
                       'next_text' => is_rtl() ? 'التالي' : 'Next »',
                       'type'      => 'plain',
                   ));
               }

               $wp_query = $orig_query; // fix for pagination to work

               if ( null !== $orig_paged ) {
                   $paged = $orig_paged;
               } else {
                   unset( $paged );
               }

               if ( null !== $orig_page ) {
                   $page = $orig_page;
               } else {
                   unset( $page );
               }

               set_query_var( 'paged', $main_query_paged );
               set_query_var( 'page', $main_query_page );

               if ( $pagination ) {
                   echo $pagination; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Output generated by theme_pagination()/paginate_links().
               }
            ?>
          </div>
        </div>
      <?php endif; endif; wp_reset_postdata(); ?>
    		</div>
    	</div>
    </div>

    <?php if ( !empty(get_the_content()) || get_the_content() !== "" ): ?>
    <div class="project-main">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="content-box maincontent">
            <?php wpautop(the_content()); ?>
            </div>
          </div>
        </div>
      </div>
    </div>
    <?php endif; ?>
<?php

// Jawda header
get_my_footer();